# LSTM文本生成

In [1]:
#文本数据加载
data = open('task2_data').read()
#移除换行符
data = data.replace('\n','').replace('\r','')
print(data)


Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals.Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of "intelligent agents": any device that perceives its environment and takes actions that maximize its chance of successfully achieving its goals.Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines, unlike the natural intelligence displayed by humans and animals. Leading AI textbooks define the field as the study of "intelligent agents": an

In [2]:
#字符字母的去重处理
letters = list(set(data))
print(letters)
features = len(letters)
print(features)

[':', 'c', 'h', 'y', 'n', 'b', 'z', 'o', 'k', ' ', 'u', 'p', 'r', ')', '.', 'v', 'd', 'A', '(', 't', 'I', 'f', 'a', 'e', 'l', 'L', 'i', 'm', ',', '"', 'g', 'x', 's']
33


In [3]:
#建立字典
#数字：字符字典
int_to_char = {a:b for a,b in enumerate(letters)}
print(int_to_char)
#字符：数字字典
char_to_int = {b:a for a,b in enumerate(letters)}
print(char_to_int)

{0: ':', 1: 'c', 2: 'h', 3: 'y', 4: 'n', 5: 'b', 6: 'z', 7: 'o', 8: 'k', 9: ' ', 10: 'u', 11: 'p', 12: 'r', 13: ')', 14: '.', 15: 'v', 16: 'd', 17: 'A', 18: '(', 19: 't', 20: 'I', 21: 'f', 22: 'a', 23: 'e', 24: 'l', 25: 'L', 26: 'i', 27: 'm', 28: ',', 29: '"', 30: 'g', 31: 'x', 32: 's'}
{':': 0, 'c': 1, 'h': 2, 'y': 3, 'n': 4, 'b': 5, 'z': 6, 'o': 7, 'k': 8, ' ': 9, 'u': 10, 'p': 11, 'r': 12, ')': 13, '.': 14, 'v': 15, 'd': 16, 'A': 17, '(': 18, 't': 19, 'I': 20, 'f': 21, 'a': 22, 'e': 23, 'l': 24, 'L': 25, 'i': 26, 'm': 27, ',': 28, '"': 29, 'g': 30, 'x': 31, 's': 32}


In [4]:
#time_step
time_step = 30

In [5]:
import numpy as np
from keras.utils import to_categorical
#滑动窗口提取数据
def extract_data(data, slide):    
    x = []
    y = []    
    for i in range(len(data) - slide):
        x.append([a for a in data[i:i+slide]])
        y.append(data[i+slide])        
    return x,y
#字符到数字的批量转化
def char_to_int_Data(x,y, char_to_int):    
    x_to_int = []
    y_to_int = []
    for i in range(len(x)):
        x_to_int.append([char_to_int[char] for char in x[i]])
        y_to_int.append([char_to_int[char] for char in y[i]])    
    return x_to_int, y_to_int
#实现输入字符文章的批量处理，输入整个字符、滑动窗口大小、转化字典
def data_preprocessing(data, slide, num_letters, char_to_int):    
    char_Data = extract_data(data, slide)
    int_Data = char_to_int_Data(char_Data[0], char_Data[1], char_to_int)
    Input = int_Data[0]
    Output = list(np.array(int_Data[1]).flatten())
    Input_RESHAPED = np.array(Input).reshape(len(Input), slide)
    new = np.random.randint(0,10,size=[Input_RESHAPED.shape[0],Input_RESHAPED.shape[1],num_letters])
    for i in range(Input_RESHAPED.shape[0]):
        for j in range(Input_RESHAPED.shape[1]):
            new[i,j,:] = to_categorical(Input_RESHAPED[i,j],num_classes=num_letters)
    return new, Output

Using TensorFlow backend.


In [6]:
#字符串处理
# print(data)
X, y = data_preprocessing(data,time_step,features,char_to_int)
print(X[0,:,:])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [7]:
print(X[0,:,:].shape)

(30, 33)


In [8]:
print(y)

[32, 7, 27, 23, 19, 26, 27, 23, 32, 9, 1, 22, 24, 24, 23, 16, 9, 27, 22, 1, 2, 26, 4, 23, 9, 26, 4, 19, 23, 24, 24, 26, 30, 23, 4, 1, 23, 28, 9, 26, 32, 9, 26, 4, 19, 23, 24, 24, 26, 30, 23, 4, 1, 23, 9, 16, 23, 27, 7, 4, 32, 19, 12, 22, 19, 23, 16, 9, 5, 3, 9, 27, 22, 1, 2, 26, 4, 23, 32, 28, 9, 10, 4, 24, 26, 8, 23, 9, 19, 2, 23, 9, 4, 22, 19, 10, 12, 22, 24, 9, 26, 4, 19, 23, 24, 24, 26, 30, 23, 4, 1, 23, 9, 16, 26, 32, 11, 24, 22, 3, 23, 16, 9, 5, 3, 9, 2, 10, 27, 22, 4, 32, 9, 22, 4, 16, 9, 22, 4, 26, 27, 22, 24, 32, 14, 9, 25, 23, 22, 16, 26, 4, 30, 9, 17, 20, 9, 19, 23, 31, 19, 5, 7, 7, 8, 32, 9, 16, 23, 21, 26, 4, 23, 9, 19, 2, 23, 9, 21, 26, 23, 24, 16, 9, 22, 32, 9, 19, 2, 23, 9, 32, 19, 10, 16, 3, 9, 7, 21, 9, 29, 26, 4, 19, 23, 24, 24, 26, 30, 23, 4, 19, 9, 22, 30, 23, 4, 19, 32, 29, 0, 9, 22, 4, 3, 9, 16, 23, 15, 26, 1, 23, 9, 19, 2, 22, 19, 9, 11, 23, 12, 1, 23, 26, 15, 23, 32, 9, 26, 19, 32, 9, 23, 4, 15, 26, 12, 7, 4, 27, 23, 4, 19, 9, 22, 4, 16, 9, 19, 22, 8, 23, 32, 9

In [9]:
print(X.shape,len(y))

(11160, 30, 33) 11160


In [10]:
#数据分离
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=0)
print(X.shape,X_train.shape,X_test.shape)
print(len(y),len(y_train),len(y_test))

(11160, 30, 33) (10044, 30, 33) (1116, 30, 33)
11160 10044 1116


In [11]:
#输出结果的格式转化
y_train_c = to_categorical(y_train,features)
print(y_train)
print(y_train_c)

[23, 23, 9, 9, 26, 9, 26, 30, 1, 32, 22, 23, 22, 9, 23, 9, 23, 23, 7, 8, 30, 24, 24, 19, 4, 17, 9, 4, 32, 26, 22, 9, 24, 30, 5, 32, 23, 23, 1, 7, 19, 26, 26, 9, 22, 4, 23, 12, 23, 9, 32, 9, 26, 22, 28, 9, 4, 24, 23, 27, 26, 26, 21, 24, 21, 32, 11, 25, 7, 9, 9, 23, 32, 4, 21, 5, 9, 30, 9, 26, 26, 7, 23, 23, 9, 26, 10, 30, 2, 4, 19, 23, 26, 16, 0, 9, 9, 23, 9, 26, 26, 26, 20, 24, 1, 24, 16, 32, 4, 26, 31, 15, 31, 15, 9, 27, 1, 32, 22, 15, 9, 1, 32, 22, 4, 9, 22, 2, 10, 17, 32, 9, 23, 22, 4, 9, 7, 9, 23, 16, 23, 1, 4, 18, 8, 19, 10, 16, 8, 26, 19, 10, 9, 4, 19, 19, 9, 9, 32, 16, 26, 19, 4, 24, 16, 20, 23, 23, 23, 27, 4, 9, 26, 4, 4, 9, 12, 27, 30, 32, 31, 9, 22, 22, 27, 1, 9, 32, 26, 27, 24, 19, 26, 9, 9, 9, 16, 9, 16, 9, 23, 32, 23, 19, 4, 19, 23, 4, 21, 23, 27, 9, 4, 4, 11, 23, 9, 19, 32, 4, 7, 26, 32, 11, 31, 26, 19, 27, 9, 6, 29, 3, 9, 27, 12, 4, 5, 9, 29, 9, 4, 23, 3, 9, 19, 7, 9, 7, 22, 9, 9, 8, 4, 23, 32, 2, 9, 15, 26, 19, 9, 10, 32, 14, 32, 4, 19, 23, 9, 27, 14, 19, 24, 2, 28, 32,

In [12]:
print(y_train_c.shape)

(10044, 33)


In [13]:
#建立LSTM模型
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
#LSTM层
model.add(LSTM(units=30, input_shape=(X_train.shape[1],X_train.shape[2]),activation='relu'))
#输出层
model.add(Dense(units=features,activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 30)                7680      
_________________________________________________________________
dense_1 (Dense)              (None, 33)                1023      
Total params: 8,703
Trainable params: 8,703
Non-trainable params: 0
_________________________________________________________________


In [14]:
#核心参数配置
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [15]:
#模型训练
model.fit(X_train,y_train_c,batch_size=1000,epochs=50)

Epoch 1/50
10044/10044 [==============================] - 2s 183us/step - loss: 3.4804 - accuracy: 0.0903
Epoch 2/50
10044/10044 [==============================] - 1s 145us/step - loss: 3.4233 - accuracy: 0.1245
Epoch 3/50
10044/10044 [==============================] - 1s 138us/step - loss: 3.2554 - accuracy: 0.1306
Epoch 4/50
10044/10044 [==============================] - 1s 139us/step - loss: 3.0913 - accuracy: 0.1440
Epoch 5/50
10044/10044 [==============================] - 1s 137us/step - loss: 2.9834 - accuracy: 0.1523
Epoch 6/50
10044/10044 [==============================] - 1s 142us/step - loss: 2.9365 - accuracy: 0.1916
Epoch 7/50
10044/10044 [==============================] - 1s 144us/step - loss: 2.9057 - accuracy: 0.1517
Epoch 8/50
10044/10044 [==============================] - 1s 142us/step - loss: 2.8831 - accuracy: 0.1823
Epoch 9/50
10044/10044 [==============================] - 1s 135us/step - loss: 2.8580 - accuracy: 0.1775
Epoch 10/50
10044/10044 [=====================

In [16]:
#训练数据的预测
y_train_predict = model.predict_classes(X_train)
print(y_train_predict)

[23 26  9 ... 23  4 16]


In [17]:
#预测结果转化到字符
y_train_predict_char = [int_to_char[i] for i in y_train_predict]
print(y_train_predict_char)

['e', 'i', ' ', 'c', 'i', ' ', 'i', 'n', 'c', 'e', 'a', 'n', 'a', ' ', 'e', ' ', 'n', 'e', 'o', 'n', 'g', ' ', 'l', 'a', 'n', ' ', 's', 'n', 'm', 's', 'a', ' ', 'l', 'g', 'b', 'c', 'n', 'a', 'n', 'o', 'i', ',', 'i', ' ', 'a', 'c', 'i', 'r', 'e', 'c', 'h', ' ', 'i', 'a', ',', ' ', 'n', 'l', 'e', 'm', 'i', 'i', 'f', 'l', 't', 's', ' ', 'a', 'o', 'c', ' ', 'e', 's', 'n', 'f', 'm', ' ', 'g', ' ', 's', 'i', 'o', 'i', 'e', ' ', 'i', 'u', 'g', 'h', 'n', ' ', 'e', 'i', 'd', 'i', ' ', ' ', 'a', ' ', 'a', 'i', 'i', 'I', 'l', 'c', 'l', 'a', ' ', 'n', 'i', 'x', 'v', 'x', 't', ' ', 'm', 'c', 'f', 'a', 'v', ' ', 'c', 'i', 'a', 'n', ' ', 'a', 'h', 'u', 'a', 's', ' ', 'e', 'a', 'n', ' ', 'e', ' ', 'n', 'd', 'e', 'c', 'n', 'd', 's', 't', 'u', 'd', 'n', 'i', 't', 'u', ' ', 'n', 's', 'c', ' ', ' ', 's', 'd', 'i', 't', 'n', 'n', 'd', 'I', 'e', 'e', 'e', 'm', 'n', ' ', 's', 'n', 'n', ' ', 'r', 'm', 'a', ' ', ' ', ' ', 'A', 'a', 'm', 'c', ' ', 's', 'i', 'm', 'l', 't', 'i', ' ', ' ', ' ', 'd', ' ', 'a', ' ',

In [18]:
#准确率
from sklearn.metrics import accuracy_score
accuracy_train = accuracy_score(y_train,y_train_predict)
print(accuracy_train)

0.7296893667861409


In [19]:
#测试数据的预测
y_test_predict = model.predict_classes(X_test)
y_test_predict_char = [int_to_char[i] for i in y_test_predict]
print(y_test_predict_char)

['a', 'i', 's', 'g', 'n', 'n', 'l', 'i', ' ', 'e', 'n', 't', 'm', 'l', 'a', 'r', ' ', 'c', 'i', ' ', 'n', 'r', 'i', 't', 'e', 'm', 'g', 'r', ' ', 'r', ' ', ' ', 'u', 'k', 'a', 'c', 's', ' ', 'i', 'e', 'i', 's', 'c', 'm', ' ', 'l', 'm', 'f', 'l', 'l', 's', 'n', 'n', 'n', ' ', 'e', 'e', 'e', ' ', 'a', 'm', ' ', 'e', 'd', 't', ' ', 'n', 'd', 'c', ' ', 'c', 't', 'A', 'i', 'o', ' ', 'x', 'e', 'e', 'n', 'u', ' ', 'e', 'A', 'c', ' ', 'n', ' ', 'n', 'a', 'u', 'e', ',', 'h', 'a', 'l', 'c', ' ', 'f', ' ', 'n', 'f', 'i', 'm', 'I', 'a', 't', 'o', ' ', ' ', 'm', 'l', 'b', ' ', ' ', 's', 'e', 'n', ' ', 'e', ' ', 'e', 'c', 'l', 'f', 'a', 'b', 'm', 'i', 'i', 'l', 'a', ' ', 'm', 'l', 'c', 'e', 's', ' ', 'a', 'g', 'd', ' ', 'v', 't', 't', 'l', 'm', ' ', 'e', 'g', ' ', 'm', 'e', 'a', 'e', ' ', 'g', 'i', ' ', ' ', ' ', 's', 's', 'e', 'g', 's', 'm', 'd', 'y', ' ', 's', 'o', 'i', 'i', 'a', 't', 't', ' ', 'a', 'u', 'a', ' ', 'm', 'n', 'h', 'b', 'e', ' ', 's', 's', 'e', 'n', ' ', 'l', 'n', 'e', 'n', ' ', 'a',

In [20]:
accuracy_test = accuracy_score(y_test,y_test_predict)
print(accuracy_test)

0.6980286738351255


In [21]:
#新字符串的预测
new_letters = 'Artificial intelligence (AI), sometimes called machine intelligence, is intelligence demonstrated by machines'
X_new,y_new = data_preprocessing(new_letters,time_step,features,char_to_int)
print(X_new.shape,len(y_new))

(79, 30, 33) 79


In [22]:
y_new_predict = model.predict_classes(X_new)
print(y_new_predict)

[32  7 27 23 32 26 27 23  4  9  1 22 24 24 23 16  9 27 22  1  2 26  4 23
  9 28  4 19 23 24 24 26 30 23  4  1 23  9  9 26 32  9 26  4 19 23 24 24
 26 30 23  4  1 23  9 16 23 27  7  4  1 19 12 22 19 23 16  9  5  3  9 27
 22  1  2 26  4 23 32]


In [23]:
y_new_predict_char = [int_to_char[i] for i in y_new_predict]
print(y_new_predict_char)

['s', 'o', 'm', 'e', 's', 'i', 'm', 'e', 'n', ' ', 'c', 'a', 'l', 'l', 'e', 'd', ' ', 'm', 'a', 'c', 'h', 'i', 'n', 'e', ' ', ',', 'n', 't', 'e', 'l', 'l', 'i', 'g', 'e', 'n', 'c', 'e', ' ', ' ', 'i', 's', ' ', 'i', 'n', 't', 'e', 'l', 'l', 'i', 'g', 'e', 'n', 'c', 'e', ' ', 'd', 'e', 'm', 'o', 'n', 'c', 't', 'r', 'a', 't', 'e', 'd', ' ', 'b', 'y', ' ', 'm', 'a', 'c', 'h', 'i', 'n', 'e', 's']


In [24]:
for i in range(0,X_new.shape[0]-30):
    print(new_letters[i:i+30],'--predict new letter is>>>',y_new_predict_char[i])

Artificial intelligence (AI),  --predict new letter is>>> s
rtificial intelligence (AI), s --predict new letter is>>> o
tificial intelligence (AI), so --predict new letter is>>> m
ificial intelligence (AI), som --predict new letter is>>> e
ficial intelligence (AI), some --predict new letter is>>> s
icial intelligence (AI), somet --predict new letter is>>> i
cial intelligence (AI), someti --predict new letter is>>> m
ial intelligence (AI), sometim --predict new letter is>>> e
al intelligence (AI), sometime --predict new letter is>>> n
l intelligence (AI), sometimes --predict new letter is>>>  
 intelligence (AI), sometimes  --predict new letter is>>> c
intelligence (AI), sometimes c --predict new letter is>>> a
ntelligence (AI), sometimes ca --predict new letter is>>> l
telligence (AI), sometimes cal --predict new letter is>>> l
elligence (AI), sometimes call --predict new letter is>>> e
lligence (AI), sometimes calle --predict new letter is>>> d
ligence (AI), sometimes called --predict

![materials](materials2.png)